name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@d54b1d709064c76626a2bc3efe526a6ae5ab8749
    with:
      config-path: .github/labeler.yml
    secrets: inherit
