name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@178684fb03474efd13342ef67ff2a20ffec24e34
    with:
      config-path: .github/labeler.yml
    secrets: inherit
