name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@83cef8d36a5b59839a19d61f34bd3dda30c8b7c9
    with:
      config-path: .github/labeler.yml
    secrets: inherit
